version: '3'
services:
 python:
  build: .
  container_name: python-training
  volumes:
   - './working:/working/'
  ports:
   - '8888:8888'
  tty: true
  command: jupyter notebook --allow-root --ip=0.0.0.0